### ISSUE TITLE
Upgrading @okta/okta-client-nodejs to v4.3.1 causes execution errors

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/graph-okta#118]
The following is handled after deploying this project with @okta/okta-client-nodejs to v4.3.1. I believe this PR is responsible: https://github.com/okta/okta-sdk-nodejs/pull/203

Unfortunately, it does not seem to be easy to isolate this in local tests. May benefit from creating a docker env to test.

I tried the obvious solution of requiring `node-fetch` as a dependency of `graph-okta` but that did not solve the problem.

```shell
Caused by: TypeError: realFetch.call is not a function
 at Object.module.exports [as default] (/var/task/webpack:/node_modules/isomorphic-fetch/fetch-npm-node.js:8:19)
 at /var/task/webpack:/node_modules/@jupiterone/graph-okta/dist/invocationValidator.js:39:28
 at Generator.next (<anonymous>)
 at asyncGeneratorStep (/var/task/jupiter-integration-okta.js:63967:103)
 at _next (/var/task/jupiter-integration-okta.js:63969:194)
 at /var/task/jupiter-integration-okta.js:63969:364
 at new Promise (<anonymous>)
 at /var/task/jupiter-integration-okta.js:63969:97
 at invocationValidator (/var/task/jupiter-integration-okta.js:64007:31)
 at invokeInvocationValidator (webpack:///./src/integration/execution/invokeInvocationValidator.ts?:16:11)
```

**Comment by kevincasey1222** [comment]
The rewrite of Okta for the new SDK is set to use okta client 4.5.1. Once that is deployed, we should see whether this problem is still happening. If it is, the new SDK will work just fine with the old okta version (which is 3.0.0).

**Comment by aiwilliams** [comment]
This is not happening after deploying @kevincasey1222's changes to production.
